// Copyright 2021-2026 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.15.0 with parameter "bootstrap_wkt=true,target=ts,import_extension=js,json_types=true"
// @generated from file google/protobuf/c_sharp_features.proto (package pb, syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "../../../codegenv2/types.js";
import { fileDesc } from "../../../codegenv2/file.js";
import type { FeatureSet } from "./descriptor_pb.js";
import { file_google_protobuf_descriptor } from "./descriptor_pb.js";
import type { Message } from "../../../types.js";
import { messageDesc } from "../../../codegenv2/message.js";
import { extDesc } from "../../../codegenv2/extension.js";

/**
 * Describes the file google/protobuf/c_sharp_features.proto.
 */
export const file_google_protobuf_c_sharp_features: GenFile = /*@__PURE__*/
  fileDesc("CiZnb29nbGUvcHJvdG9idWYvY19zaGFycF9mZWF0dXJlcy5wcm90bxICcGIiUwoOQ1NoYXJwRmVhdHVyZXMSQQoYbnVsbGFibGVfcmVmZXJlbmNlX3R5cGVzGAEgASgIQh+IAQGYAQSYAQOYAQGiAQoSBWZhbHNlGIQHsgEDCOoHOkgKBmNzaGFycBIbLmdvb2dsZS5wcm90b2J1Zi5GZWF0dXJlU2V0GOwHIAEoCzISLnBiLkNTaGFycEZlYXR1cmVzUgZjc2hhcnBCOUIYQ1NoYXJwRmVhdHVyZXNPdXRlckNsYXNzUAGqAhpHb29nbGUuUHJvdG9idWYuUmVmbGVjdGlvbg", [file_google_protobuf_descriptor]);

/**
 * @generated from message pb.CSharpFeatures
 */
export type CSharpFeatures = Message<"pb.CSharpFeatures"> & {
  /**
   * Whether the generated files should have nullable reference type annotations.
   * When enabled, the generated C# code includes `#nullable enable annotations`
   * and annotates message-typed properties and certain parameters with `?`.
   *
   * @generated from field: optional bool nullable_reference_types = 1;
   */
  nullableReferenceTypes: boolean;
};

/**
 * @generated from message pb.CSharpFeatures
 */
export type CSharpFeaturesJson = {
  /**
   * Whether the generated files should have nullable reference type annotations.
   * When enabled, the generated C# code includes `#nullable enable annotations`
   * and annotates message-typed properties and certain parameters with `?`.
   *
   * @generated from field: optional bool nullable_reference_types = 1;
   */
  nullableReferenceTypes?: boolean;
};

/**
 * Describes the message pb.CSharpFeatures.
 * Use `create(CSharpFeaturesSchema)` to create a new message.
 */
export const CSharpFeaturesSchema: GenMessage<CSharpFeatures, {jsonType: CSharpFeaturesJson}> = /*@__PURE__*/
  messageDesc(file_google_protobuf_c_sharp_features, 0);

/**
 * @generated from extension: optional pb.CSharpFeatures csharp = 1004;
 */
export const csharp: GenExtension<FeatureSet, CSharpFeatures> = /*@__PURE__*/
  extDesc(file_google_protobuf_c_sharp_features, 0);

