// Copyright 2021-2026 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.15.0 with parameter "bootstrap_wkt=true,target=ts,import_extension=js,json_types=true"
// @generated from file google/protobuf/cpp_file_options.proto (package pb.file, edition 2024)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "../../../codegenv2/types.js";
import { fileDesc } from "../../../codegenv2/file.js";
import type { FileOptions } from "./descriptor_pb.js";
import { file_google_protobuf_descriptor } from "./descriptor_pb.js";
import type { Message } from "../../../types.js";
import { messageDesc } from "../../../codegenv2/message.js";
import { extDesc } from "../../../codegenv2/extension.js";

/**
 * Describes the file google/protobuf/cpp_file_options.proto.
 */
export const file_google_protobuf_cpp_file_options: GenFile = /*@__PURE__*/
  fileDesc("CiZnb29nbGUvcHJvdG9idWYvY3BwX2ZpbGVfb3B0aW9ucy5wcm90bxIHcGIuZmlsZSIlCg5DcHBGaWxlT3B0aW9ucxIRCgluYW1lc3BhY2UYASABKAlYATpQCgNjcHASHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMY3gcgASgLMhcucGIuZmlsZS5DcHBGaWxlT3B0aW9uc0IGsgEDCOoHUgNjcHBiCGVkaXRpb25zcOkH", [file_google_protobuf_descriptor]);

/**
 * @generated from message pb.file.CppFileOptions
 */
export type CppFileOptions = Message<"pb.file.CppFileOptions"> & {
  /**
   * Use this option to change the namespace of cpp generated classes. When this
   * option is not set, the package name will be used for determining the cpp
   * namespace.
   *
   * @generated from field: string namespace = 1;
   */
  namespace: string;
};

/**
 * @generated from message pb.file.CppFileOptions
 */
export type CppFileOptionsJson = {
  /**
   * Use this option to change the namespace of cpp generated classes. When this
   * option is not set, the package name will be used for determining the cpp
   * namespace.
   *
   * @generated from field: string namespace = 1;
   */
  namespace?: string;
};

/**
 * Describes the message pb.file.CppFileOptions.
 * Use `create(CppFileOptionsSchema)` to create a new message.
 */
export const CppFileOptionsSchema: GenMessage<CppFileOptions, {jsonType: CppFileOptionsJson}> = /*@__PURE__*/
  messageDesc(file_google_protobuf_cpp_file_options, 0);

/**
 * @generated from extension: pb.file.CppFileOptions cpp = 990;
 */
export const cpp: GenExtension<FileOptions, CppFileOptions> = /*@__PURE__*/
  extDesc(file_google_protobuf_cpp_file_options, 0);

