// Copyright 2021-2026 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.15.0 with parameter "bootstrap_wkt=true,target=ts,import_extension=js,json_types=true"
// @generated from file google/protobuf/cpp_options.proto (package pb, edition 2024)
/* eslint-disable */

import type { GenFile } from "../../../codegenv2/types.js";
import { fileDesc } from "../../../codegenv2/file.js";
import { file_google_protobuf_cpp_file_options } from "./cpp_file_options_pb.js";

/**
 * Describes the file google/protobuf/cpp_options.proto.
 */
export const file_google_protobuf_cpp_options: GenFile = /*@__PURE__*/
  fileDesc("CiFnb29nbGUvcHJvdG9idWYvY3BwX29wdGlvbnMucHJvdG8SAnBiUABiCGVkaXRpb25zcOkH", [file_google_protobuf_cpp_file_options]);

