// Copyright 2021-2026 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.15.0 with parameter "bootstrap_wkt=true,target=ts,import_extension=js,json_types=true"
// @generated from file google/protobuf/json_enumvalue_options.proto (package pb.enumvalue, edition 2024)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "../../../codegenv2/types.js";
import { fileDesc } from "../../../codegenv2/file.js";
import type { EnumValueOptions } from "./descriptor_pb.js";
import { file_google_protobuf_descriptor } from "./descriptor_pb.js";
import type { Message } from "../../../types.js";
import { messageDesc } from "../../../codegenv2/message.js";
import { extDesc } from "../../../codegenv2/extension.js";

/**
 * Describes the file google/protobuf/json_enumvalue_options.proto.
 */
export const file_google_protobuf_json_enumvalue_options: GenFile = /*@__PURE__*/
  fileDesc("Cixnb29nbGUvcHJvdG9idWYvanNvbl9lbnVtdmFsdWVfb3B0aW9ucy5wcm90bxIMcGIuZW51bXZhbHVlIigKFEpzb25FbnVtVmFsdWVPcHRpb25zEg4KBnN0cmluZxgBIAEoCVgBOmIKBGpzb24SIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjmByABKAsyIi5wYi5lbnVtdmFsdWUuSnNvbkVudW1WYWx1ZU9wdGlvbnNCBrIBAwjqB1IEanNvbkIaChhjb20uZ29vZ2xlLnByb3RvYnVmLnV0aWxiCGVkaXRpb25zcOkH", [file_google_protobuf_descriptor]);

/**
 * @generated from message pb.enumvalue.JsonEnumValueOptions
 */
export type JsonEnumValueOptions = Message<"pb.enumvalue.JsonEnumValueOptions"> & {
  /**
   * Allows user to specify a custom string to use when serializing an enum
   * value to JSON.
   *
   * Sample usage:
   * enum Foo {
   *   ...
   *   FOO_BAR = 42 [(pb.enumvalue.json).string = "my_custom_name"];
   * }
   *
   * @generated from field: string string = 1;
   */
  string: string;
};

/**
 * @generated from message pb.enumvalue.JsonEnumValueOptions
 */
export type JsonEnumValueOptionsJson = {
  /**
   * Allows user to specify a custom string to use when serializing an enum
   * value to JSON.
   *
   * Sample usage:
   * enum Foo {
   *   ...
   *   FOO_BAR = 42 [(pb.enumvalue.json).string = "my_custom_name"];
   * }
   *
   * @generated from field: string string = 1;
   */
  string?: string;
};

/**
 * Describes the message pb.enumvalue.JsonEnumValueOptions.
 * Use `create(JsonEnumValueOptionsSchema)` to create a new message.
 */
export const JsonEnumValueOptionsSchema: GenMessage<JsonEnumValueOptions, {jsonType: JsonEnumValueOptionsJson}> = /*@__PURE__*/
  messageDesc(file_google_protobuf_json_enumvalue_options, 0);

/**
 * @generated from extension: pb.enumvalue.JsonEnumValueOptions json = 998;
 */
export const json: GenExtension<EnumValueOptions, JsonEnumValueOptions> = /*@__PURE__*/
  extDesc(file_google_protobuf_json_enumvalue_options, 0);

